(()=>{
const c=window.APP_CONFIG||{};if(!c.supabaseUrl||!c.supabaseAnonKey||!window.supabase||window.__dr)return;window.__dr=1;
const db=window.supabase.createClient(c.supabaseUrl,c.supabaseAnonKey);let busy=0,t;
const $=s=>document.querySelector(s),esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m])),n=v=>new Intl.NumberFormat('id-ID').format(+v||0);
const dash=()=>($('#pageTitle')?.textContent||'').trim().toLowerCase()==='dashboard';
async function school(){const {data:{user}}=await db.auth.getUser();if(!user)return null;const {data,error}=await db.from('profiles').select('school_id').eq('id',user.id).single();if(error)throw error;return data?.school_id}
function calc(ss,es){const active=ss.filter(s=>s.status==='Aktif'),cm=new Map(),cv=new Map(),vm=new Map(),sm=new Map(),am=new Map();active.forEach(s=>{let k=s.class_name||'Belum diisi';cm.set(k,(cm.get(k)||0)+1)});const v=es.filter(e=>e.event_type==='pelanggaran'||(!e.event_type&&+e.points>0)),a=es.filter(e=>e.event_type==='prestasi'||(!e.event_type&&+e.points<0)),s=es.filter(e=>e.event_type==='sanksi');v.forEach(e=>{let k=e.students?.class_name||'Belum diisi';cv.set(k,(cv.get(k)||0)+1);k=e.violation_types?.name||'Pelanggaran lain';vm.set(k,(vm.get(k)||0)+1)});s.forEach(e=>{let k=e.sanction_levels?.action||'Sanksi lain';sm.set(k,(sm.get(k)||0)+1)});a.forEach(e=>{if(!e.student_id)return;let x=am.get(e.student_id)||{name:e.students?.name||'Siswa',cl:e.students?.class_name||'-',count:0,points:0};x.count++;x.points+=Math.abs(+e.points||0);am.set(e.student_id,x)});let sort=m=>[...m].sort((x,y)=>y[1]-x[1]).map(([name,count])=>({name,count}));return{total:active.length,classes:sort(cm),classV:sort(cv),viol:sort(vm).slice(0,8),san:sort(sm).slice(0,6),ach:[...am.values()].sort((x,y)=>y.points-x.points||y.count-x.count).slice(0,5),vt:v.length,at:a.length,st:s.length}}
function bars(rows,max){return rows.length?rows.map((r,i)=>`<div class="dr-row"><div><span>${i+1}. ${esc(r.name)}</span><b>${n(r.count)}</b></div><i><em style="width:${Math.max(5,r.count/max*100)}%"></em></i></div>`).join(''):'<div class="dr-empty">Belum ada data.</div>'}
function pie(rows){if(!rows.length)return'<div class="dr-no-pie">Belum ada pelanggaran.</div>';let total=rows.reduce((a,x)=>a+x.count,0),cur=0,st=rows.slice(0,6).map((x,i)=>{let z=cur;cur+=x.count/total*360;return`var(--dc${i}) ${z}deg ${cur}deg`}).join(',');return`<div class="dr-piebox"><div class="dr-pie" style="background:conic-gradient(${st})"><div><strong>${Math.round(rows[0].count/total*100)}%</strong><span>${esc(rows[0].name)}</span></div></div><div class="dr-legend">${rows.slice(0,6).map((x,i)=>`<div><i class="dr-dot dc${i}"></i><span>${esc(x.name)}</span><b>${Math.round(x.count/total*100)}%</b></div>`).join('')}</div></div>`}
function render(d){let cm=Math.max(1,...d.classes.map(x=>x.count)),vm=Math.max(1,...d.viol.map(x=>x.count));$('#page').innerHTML=`<div class="dashboard-recap"><div class="dr-head"><div><span class="eyebrow">RINGKASAN SEKOLAH</span><h1>Dashboard</h1><p>Rekap disiplin, siswa, prestasi, dan sanksi dalam satu tampilan.</p></div></div><div class="dr-stats"><div class="dr-stat"><span>Total siswa aktif</span><strong>${n(d.total)}</strong><small>Data siswa aktif</small></div><div class="dr-stat"><span>Total pelanggaran</span><strong>${n(d.vt)}</strong><small>Catatan kejadian</small></div><div class="dr-stat"><span>Total prestasi</span><strong>${n(d.at)}</strong><small>Catatan prestasi</small></div><div class="dr-stat"><span>Total sanksi</span><strong>${n(d.st)}</strong><small>Catatan sanksi</small></div></div><div class="dr-grid"><article class="dr-card"><header><div><span class="eyebrow">DISTRIBUSI SISWA</span><h2>Jumlah siswa setiap kelas</h2></div><b>${n(d.total)} siswa</b></header><div class="dr-classes">${d.classes.length?d.classes.map(x=>`<div><span>${esc(x.name)}</span><i><em style="width:${Math.max(5,x.count/cm*100)}%"></em></i><b>${n(x.count)}</b></div>`).join(''):'<div class="dr-empty">Belum ada data kelas.</div>'}</div></article><article class="dr-card"><header><div><span class="eyebrow">DISTRIBUSI PELANGGARAN</span><h2>Kelas dengan pelanggaran terbanyak</h2></div></header>${pie(d.classV)}</article></div><div class="dr-grid"><article class="dr-card"><header><div><span class="eyebrow">TOP PELANGGARAN</span><h2>Pelanggaran paling banyak</h2><p>Urutan berdasarkan jumlah kejadian.</p></div></header><div>${bars(d.viol,vm)}</div></article><article class="dr-card"><header><div><span class="eyebrow">SANKSI</span><h2>Sanksi paling sering</h2></div></header><div class="dr-san">${d.san.length?d.san.map((x,i)=>`<div><i>${i+1}</i><span>${esc(x.name)}</span><b>${n(x.count)}</b></div>`).join(''):'<div class="dr-empty">Belum ada data sanksi.</div>'}</div></article></div><article class="dr-ach"><header><div><span class="eyebrow">PRESTASI SISWA</span><h2>Siswa paling berprestasi</h2><p>Peringkat berdasarkan total poin prestasi.</p></div></header><div>${d.ach.length?d.ach.map((x,i)=>`<div><i>${i+1}</i><span><strong>${esc(x.name)}</strong><small>${esc(x.cl)} · ${n(x.count)} prestasi</small></span><b>${n(x.points)} poin</b></div>`).join(''):'<div class="dr-empty">Belum ada data prestasi siswa.</div>'}</div></article><div class="dr-note">Dashboard hanya untuk melihat rekap. Pengelolaan data dilakukan melalui navigasi.</div></div>`}
async function load(){if(busy||!dash())return;busy=1;try{let id=await school();if(!id)return;let [ss,es]=await Promise.all([db.from('students').select('id,name,class_name,status').eq('school_id',id).limit(10000),db.from('discipline_events').select('id,student_id,event_type,points,students(name,class_name),violation_types(name),sanction_levels(action)').eq('school_id',id).limit(10000)]);if(ss.error)throw ss.error;if(es.error)throw es.error;if(dash())render(calc(ss.data||[],es.data||[]))}catch(e){console.error('dashboard-recap',e)}finally{busy=0}}
function schedule(){clearTimeout(t);t=setTimeout(load,180)}
window.addEventListener('load',()=>{new MutationObserver(()=>{if(dash()&&!$('#page .dashboard-recap'))schedule()}).observe(document.body,{childList:true,subtree:true});schedule()},{once:true});
})();