// Robust Excel importer for Pelanggaran, Prestasi, and Sanksi.
(() => {
 const cfg=window.APP_CONFIG||{}; if(!cfg.supabaseUrl||!cfg.supabaseAnonKey||!window.supabase)return;
 const sb=window.supabase.createClient(cfg.supabaseUrl,cfg.supabaseAnonKey);
 const $=s=>document.querySelector(s); const clean=v=>v==null?'':String(v).trim(); const norm=v=>clean(v).toLowerCase().replace(/[.]/g,'').replace(/\s+/g,' ');
 const toast=m=>{const t=$('#toast');if(!t)return;t.textContent=m;t.classList.add('show');clearTimeout(window.__dpIncidentToast);window.__dpIncidentToast=setTimeout(()=>t.classList.remove('show'),3500)};
 const today=()=>new Date().toISOString().slice(0,10);
 function date(v){if(v instanceof Date&&!isNaN(v))return v.toISOString().slice(0,10);const s=clean(v);if(!s)return today();if(/^\d{4}-\d{1,2}-\d{1,2}$/.test(s)){const [y,m,d]=s.split('-');return `${y}-${m.padStart(2,'0')}-${d.padStart(2,'0')}`};const m=s.match(/^(\d{1,2})[\/-](\d{1,2})[\/-](\d{4})$/);return m?`${m[3]}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`:''}
 const number=v=>{const s=clean(v).replace(/\s/g,'').replace(',','.');const n=Number(s);return Number.isFinite(n)?n:0};
 async function schoolId(){const{data:{user}}=await sb.auth.getUser();if(!user)throw Error('Sesi login tidak ditemukan.');const{data:p,error}=await sb.from('profiles').select('school_id').eq('id',user.id).single();if(error||!p?.school_id)throw Error('Sekolah akun belum ditemukan.');return p.school_id}
 function headerMap(row){const aliases={no:['no','nomor'],name:['nama','nama siswa','nama lengkap','siswa'],nis:['nis','nisn'],className:['kelas','nama kelas','class'],date:['tanggal','tgl','tanggal kejadian'],item:['jenis kejadian','jenis pelanggaran','pelanggaran','jenis prestasi','prestasi','jenis sanksi','sanksi','tindakan'],points:['poin','point','nilai poin'],category:['kategori','kategori pelanggaran'],description:['kronologi','keterangan','deskripsi','catatan'],recordedBy:['pencatat','dicatat oleh','guru']};const h=row.map(norm),ix={};for(const[k,als]of Object.entries(aliases))ix[k]=als.map(norm).map(a=>h.indexOf(a)).find(i=>i>=0)??-1;return ix}
 function parse(ws,sheet){const rs=window.XLSX.utils.sheet_to_json(ws,{header:1,defval:'',raw:false});const ix=headerMap(rs[0]||[]);if(ix.name<0||ix.className<0||ix.item<0)throw Error(`Sheet ${sheet}: wajib memiliki kolom Nama, Kelas, dan Jenis Kejadian/Prestasi/Sanksi.`);return rs.slice(1).map((r,i)=>({row:i+2,name:clean(r[ix.name]),nis:ix.nis>=0?clean(r[ix.nis]):'',className:clean(r[ix.className]),eventDate:date(ix.date>=0?r[ix.date]:''),item:clean(r[ix.item]),points:ix.points>=0?number(r[ix.points]):0,category:ix.category>=0?clean(r[ix.category]):'',description:ix.description>=0?clean(r[ix.description]):'',recordedBy:ix.recordedBy>=0?clean(r[ix.recordedBy]):''})).filter(x=>x.name||x.item)}
 async function ensureCategory(sid,name,points){if(!name)return null;let{data}=await sb.from('violation_categories').select('*').eq('school_id',sid).ilike('name',name).limit(1);if(data?.[0])return data[0];const p=Math.max(0,Number(points)||0);const ins=await sb.from('violation_categories').insert({school_id:sid,name,points_from:p,points_to:p,active:true}).select('*').single();if(ins.error)throw Error(`Gagal membuat kategori "${name}": ${ins.error.message}`);return ins.data}
 async function ensureViolation(sid,r,existing,categories){let v=existing.find(x=>norm(x.name)===norm(r.item));if(v)return v;const catName=r.category||'Import Excel';let cat=categories.find(x=>norm(x.name)===norm(catName));if(!cat){cat=await ensureCategory(sid,catName,r.points);categories.push(cat)}const code='IMP-'+norm(r.item).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,35).toUpperCase()+'-'+Date.now().toString(36).slice(-5);const ins=await sb.from('violation_types').insert({school_id:sid,code,name:r.item,category:cat.name,points:Math.abs(r.points),description:r.description||null}).select('*').single();if(ins.error)throw Error(`Gagal membuat Master Pelanggaran "${r.item}": ${ins.error.message}`);existing.push(ins.data);return ins.data}
 async function ensureAchievement(sid,r,existing){let a=existing.find(x=>norm(x.name)===norm(r.item));if(a)return a;const code='IMP-'+norm(r.item).replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,35).toUpperCase()+'-'+Date.now().toString(36).slice(-5);const ins=await sb.from('achievement_types').insert({school_id:sid,code,name:r.item,level:r.category||'Umum',points:Math.abs(r.points),description:r.description||null}).select('*').single();if(ins.error)throw Error(`Gagal membuat Master Prestasi "${r.item}": ${ins.error.message}`);existing.push(ins.data);return ins.data}
 async function ensureSanction(sid,r,existing){let s=existing.find(x=>norm(x.action)===norm(r.item));if(s)return s;const levelMatch=r.category.match(/\d+/);const level=levelMatch?Number(levelMatch[0]):((existing.reduce((m,x)=>Math.max(m,Number(x.level)||0),0))+1);const ins=await sb.from('sanction_levels').insert({school_id:sid,level,action:r.item,points_from:Math.max(0,r.points),points_to:Math.max(0,r.points),executor:r.recordedBy||null,notes:r.description||null}).select('*').single();if(ins.error)throw Error(`Gagal membuat Master Sanksi "${r.item}": ${ins.error.message}`);existing.push(ins.data);return ins.data}
 async function importFile(file){if(!window.XLSX)throw Error('Library Excel belum siap.');const sid=await schoolId();const wb=window.XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});const aliases=['pelanggaran','prestasi','sangsi','sanksi'];const sheets=wb.SheetNames.filter(s=>aliases.includes(norm(s)));if(!sheets.length)throw Error('Excel harus memiliki sheet Pelanggaran, Prestasi, atau Sangsi/Sanksi.');
  const [sr,vr,ar,rr,cr]=await Promise.all([sb.from('students').select('id,name,nis,class_name').eq('school_id',sid),sb.from('violation_types').select('*').eq('school_id',sid),sb.from('achievement_types').select('*').eq('school_id',sid),sb.from('sanction_levels').select('*').eq('school_id',sid),sb.from('violation_categories').select('*').eq('school_id',sid)]);if(sr.error||vr.error||ar.error||rr.error||cr.error)throw(sr.error||vr.error||ar.error||rr.error||cr.error);
  const students=sr.data||[],violations=vr.data||[],achievements=ar.data||[],sanctions=rr.data||[],categories=cr.data||[];const byNameClass=new Map(students.map(x=>[`${norm(x.name)}|${norm(x.class_name)}`,x]));const byNis=new Map(students.filter(x=>x.nis).map(x=>[norm(x.nis),x]));const all=[],problems=[];
  for(const sheet of sheets){const type=norm(sheet)==='sangsi'?'sanksi':norm(sheet);for(const r of parse(wb.Sheets[sheet],sheet)){let st=(r.nis&&byNis.get(norm(r.nis)))||byNameClass.get(`${norm(r.name)}|${norm(r.className)}`);if(!st){problems.push(`Baris ${r.row} (${sheet}): siswa "${r.name}" + kelas "${r.className}" tidak ditemukan.`);continue}if(!r.item){problems.push(`Baris ${r.row} (${sheet}): jenis catatan kosong.`);continue}if(type==='pelanggaran'){const v=await ensureViolation(sid,r,violations,categories);all.push({school_id:sid,student_id:st.id,violation_type_id:v.id,achievement_type_id:null,sanction_level_id:null,event_date:r.eventDate,points:Math.abs(r.points||v.points||0),description:r.description||null,recorded_by_name:r.recordedBy||null,event_type:'pelanggaran'});}else if(type==='prestasi'){const a=await ensureAchievement(sid,r,achievements);all.push({school_id:sid,student_id:st.id,violation_type_id:null,achievement_type_id:a.id,sanction_level_id:null,event_date:r.eventDate,points:-Math.abs(r.points||a.points||0),description:r.description||null,recorded_by_name:r.recordedBy||null,event_type:'prestasi'});}else{const s=await ensureSanction(sid,r,sanctions);all.push({school_id:sid,student_id:st.id,violation_type_id:null,achievement_type_id:null,sanction_level_id:s.id,event_date:r.eventDate,points:0,description:r.description||null,recorded_by_name:r.recordedBy||null,event_type:'sanksi'});}}}
  if(problems.length)throw Error(`Import dibatalkan karena ${problems.length} baris tidak menemukan siswa.\n\n${problems.slice(0,12).join('\n')}${problems.length>12?'\n...':''}`);for(let i=0;i<all.length;i+=100){const{error}=await sb.from('discipline_events').insert(all.slice(i,i+100));if(error)throw Error(`Gagal menyimpan catatan: ${error.message}`)}return{rows:all.length,sheets:sheets.length,mastersCreated:{violations:violations.length-vr.data.length,achievements:achievements.length-ar.data.length,sanctions:sanctions.length-rr.data.length}}}
 function template(){const wb=window.XLSX.utils.book_new(),h=['No.','Nama','NIS','Kelas','Tanggal','Jenis Kejadian','Poin','Kategori','Kronologi','Pencatat'];for(const n of ['Pelanggaran','Prestasi','Sangsi']){const ws=window.XLSX.utils.aoa_to_sheet([h,[1,'','','','',n==='Pelanggaran'?'':'',0,'','','']]);ws['!cols']=[{wch:8},{wch:28},{wch:16},{wch:18},{wch:14},{wch:30},{wch:10},{wch:20},{wch:45},{wch:25}];window.XLSX.utils.book_append_sheet(wb,ws,n)}window.XLSX.writeFile(wb,'Template_Import_Catatan_Disiplin_Pro.xlsx')}
 function install(){document.addEventListener('change',async e=>{if(e.target.id!=='incidentExcelImport')return;const f=e.target.files?.[0];if(!f)return;try{toast('Membaca Excel dan otomatis mencocokkan siswa + membuat master yang belum ada...');const r=await importFile(f);toast(`Berhasil: ${r.rows} catatan dari ${r.sheets} sheet. Master baru ikut dibuat bila belum tersedia.`);document.dispatchEvent(new CustomEvent('dp:incidents-imported',{detail:r}));document.dispatchEvent(new CustomEvent('dp:master-data-changed',{detail:r}))}catch(err){console.error('[Disiplin Pro incident import]',err);toast(err?.message||'Import gagal.')}e.target.value=''});document.addEventListener('click',e=>{if(e.target.id==='downloadIncidentTemplate')template()})}
 window.DisiplinProIncidentImport={importFile};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install);else install();
})();
